version: '3'

tasks:
  default:
    cmds:
      - task: generate
  generate:
   cmds:
      - echo "Generating protobuf code..."

      - python -c "import os; os.makedirs('./shared/gen/go', exist_ok=True); os.makedirs('./shared/gen/python', exist_ok=True)"


      #Go code generation

      - >
        protoc -I ./shared/protos/proto \
        ./shared/protos/proto/ocr/*.proto \
        --go_out=./shared/gen/go --go_opt=paths=source_relative \
        --go-grpc_out=./shared/gen/go --go-grpc_opt=paths=source_relative


      # Python code generation

      - python -m pip install --quiet --exists-action=i grpcio-tools
      - >
        python -m grpc_tools.protoc \
        -I ./shared/protos/proto \
        --python_out=./shared/gen/python \
        --grpc_python_out=./shared/gen/python \
        ./shared/protos/proto/ocr/*.proto

      - echo "Protobuf generation completed successfully."

  dockerdev-up:
    aliases:
      - dev-up
    desc: "Run development environment with Docker Compose"
    cmds:
      - echo "Starting dev environment..."
      - docker compose -f ./deployments/docker-compose-dev.yml up

  dockerdev-no-cache-up:
    aliases:
      - build-no-cache
    desc: "Building development environment with Docker Compose"
    cmds:
      - echo "Building dev environment..."
      - docker compose -f ./deployments/docker-compose-dev.yml build --no-cache 

  dockerdev-down:
    aliases:
      - dev-down
    desc: "Stop development environment"
    cmds:
      - echo  "Stopping dev environment..."
      - docker compose -f ./deployments/docker-compose-dev.yml down
  dev-build:
    aliases:
      - build
    desc: "Builds docker container in the dev mode"
    vars:
      SERVICE: '{{.SERVICE | default "backend"}}'
    cmds:
      - echo "building {{.SERVICE}}..."
      - docker compose -f ./deployments/docker-compose-dev.yml build {{.SERVICE}}
  dev-front:
    aliases:
      - front
    cmds:
    - echo "start npm run dev"
    - cd ./frontend && npm run dev