BEGIN;

CREATE TABLE IF NOT EXISTS languages (
    id       integer NOT NULL,
    language character varying(50),

    CONSTRAINT pk_languages PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS levels (
    id    integer NOT NULL,
    level character varying(50),

    CONSTRAINT pk_levels PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS users (
    id            integer NOT NULL,
    email         character varying(100),
    name          character varying(100),
    level_id      integer NOT NULL,
    lang_id       integer NOT NULL,
    words_per_day integer NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_users_levels FOREIGN KEY (level_id) REFERENCES levels(id),
    CONSTRAINT fk_users_languages FOREIGN KEY (lang_id) REFERENCES languages(id)
    );

CREATE INDEX IF NOT EXISTS idx_id ON users(id);

CREATE TABLE IF NOT EXISTS sessions (
    id         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       character varying(100),
    user_id    integer,
    status     character varying(50),
    lang_id    integer,
    started_at timestamp without time zone,
    ended_at   timestamp without time zone,
    accuracy   double precision,

    CONSTRAINT pk_sessions PRIMARY KEY (id),
    CONSTRAINT fk_sessions_languages FOREIGN KEY (lang_id) REFERENCES languages(id)
    );

CREATE INDEX IF NOT EXISTS idx_session_id ON sessions(id);

CREATE TABLE IF NOT EXISTS flashcards (
    id      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id integer,
    word    character varying(100),
    transl  character varying(100),
    lang_id integer,

    CONSTRAINT pk_flashcards PRIMARY KEY (id),
    CONSTRAINT uq_flashcards_user_word_lang UNIQUE (user_id, word, lang_id),
    CONSTRAINT flashcards_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_words_languages FOREIGN KEY (lang_id) REFERENCES languages(id)
    );

CREATE INDEX IF NOT EXISTS idx_flashcard_id ON flashcards(id);

CREATE TABLE IF NOT EXISTS decks (
    id         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    integer,
    session_id integer,

    CONSTRAINT pk_decks PRIMARY KEY (id),
    CONSTRAINT uq_decks_user_session UNIQUE (user_id, session_id),
    CONSTRAINT decks_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT decks_sessions FOREIGN KEY (session_id) REFERENCES sessions(id)
    );

CREATE INDEX IF NOT EXISTS idx_deck_id ON decks(id);

CREATE TABLE IF NOT EXISTS decks_flashcards (
    deck_id      integer NOT NULL,
    flashcard_id integer NOT NULL,

    CONSTRAINT decks_flashcards_decks FOREIGN KEY (deck_id) REFERENCES decks(id),
    CONSTRAINT decks_flashcards_flashcards FOREIGN KEY (flashcard_id) REFERENCES flashcards(id),

    PRIMARY KEY (deck_id, flashcard_id)
    );

INSERT INTO languages (id, language)
VALUES
    (1, 'english'),
    (2, 'deutsch')
    ON CONFLICT (id) DO UPDATE
    SET language = EXCLUDED.language;

INSERT INTO levels (id, level)
VALUES
    (1, 'A1'),
    (2, 'A2')
    ON CONFLICT (id) DO UPDATE
    SET level = EXCLUDED.level;

COMMIT;
